export enum ChatErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RECIPIENT_NOT_FOUND = 'RECIPIENT_NOT_FOUND',
  SELF_MESSAGE_NOT_ALLOWED = 'SELF_MESSAGE_NOT_ALLOWED',
  RATE_LIMITED = 'RATE_LIMITED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RECIPIENT_OFFLINE = 'RECIPIENT_OFFLINE',
  ACK_TIMEOUT = 'ACK_TIMEOUT',
}
